### ISSUE TITLE
Quelques questions

### ISSUE THREAD

**Issue by mikaelletang** [RETFU/REST-in-peace#1]
- quels sont les avantages de POST vs PUT sur les commandes/actions ? (techniquement, il s'agit plus de modif que de création de ressources)
- de recommandation sur ce que doit retourner POST ? La resource, ou pas de body ?
- sur Oauth2: de notre experience, on a dû rajouter une authentication par user token pour des usages limités, Oauth2 étant trop compliqué à mettre en place pour certains clients

**Comment by RETFU** [comment]
J'ai mis à jour les exemples: https://github.com/RETFU/REST-in-peace#actions
Dans le cas de translate, star, ce n'est pas forcément une modification.
L'usage est d'utiliser POST, je n'ai pas rencontré d'exceptions dans mes recherches.

https://github.com/RETFU/REST-in-peace#réponse
Lors d'un [`201 Ok`](http://httpstatus.es/201):
- on doit retourner la ressource
- on doit indiquer l'URI de la nouvelle resource dans le header `Location: https://api.domain.com/v2/items/1783`

Pour l'authentification, je l'ai retiré de la présentation, ça aurait duré trop longtemps.
C'est une partie pour le github que je dois détailler, mais oui je vois ce que tu veux dire par trop compliqué pour les clients ^^
